"""empty message

Revision ID: 73c66c6ef8e7
Revises: 17a127625772
Create Date: 2023-12-26 22:54:13.140814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '73c66c6ef8e7'
down_revision: Union[str, None] = '17a127625772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_playlist', sa.Column('video_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_playlist', 'video_title')
    # ### end Alembic commands ###
