"""empty message

Revision ID: 79b6c24427bc
Revises: 6ba02c68dc34
Create Date: 2024-01-26 21:51:00.683745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '79b6c24427bc'
down_revision: Union[str, None] = '6ba02c68dc34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpt', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gpt', 'user_id')
    # ### end Alembic commands ###
