"""empty message

Revision ID: dc737e43729d
Revises: a7aa64dea18f
Create Date: 2023-12-13 23:29:20.776471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dc737e43729d'
down_revision: Union[str, None] = 'a7aa64dea18f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crater', sa.Column('heart_list', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('crater', sa.Column('heart_num', sa.Integer(), nullable=False))
    op.add_column('crater', sa.Column('comment_num', sa.Integer(), nullable=False))
    op.drop_column('crater', 'star_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crater', sa.Column('star_list', sa.VARCHAR(), nullable=False))
    op.drop_column('crater', 'comment_num')
    op.drop_column('crater', 'heart_num')
    op.drop_column('crater', 'heart_list')
    # ### end Alembic commands ###
