"""empty message

Revision ID: fdf6dc37e2fb
Revises: 73c66c6ef8e7
Create Date: 2024-01-05 22:08:54.965595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fdf6dc37e2fb'
down_revision: Union[str, None] = '73c66c6ef8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('music_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('music_album', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('music_artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_playlist')
    # ### end Alembic commands ###
