"""empty message

Revision ID: fe80e211447b
Revises: 37edf356419f
Create Date: 2023-12-04 22:58:22.086439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fe80e211447b'
down_revision: Union[str, None] = '37edf356419f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_realname', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('user_birthday_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('user_birthday_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('user_birthday_day', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_birthday_day')
    op.drop_column('user', 'user_birthday_month')
    op.drop_column('user', 'user_birthday_year')
    op.drop_column('user', 'user_email')
    op.drop_column('user', 'user_realname')
    # ### end Alembic commands ###
